---
# tasks file for roles/jenkins

- name: install java package
  package:
    name: 
      - default-jre
    state: present

- name: Download jenkins.WAR
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc/

- name: Template a file to /etc/systemd/system/jenkins.service
  template:
    src: ./jenkins.service
    dest: /etc/systemd/system/jenkins.service
  notify:
     - restart-jenkins
     
- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Wait for the password file
  wait_for:
    path: /root/.jenkins/secrets/initialAdminPassword
    timeout: 5

- name: Get the password file
  shell: cat /root/.jenkins/secrets/initialAdminPassword
  register: res

- debug:
      var: res.stdout
