---
# tasks file for roles/jenkins

# Installing JAVA Package
- name: install java package
  package:
    name: 
      - default-jre
    state: present

# Downloads Jenkins.WAR file from remote server
- name: Download jenkins.WAR
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc/

# Template file to /etc/systemd/system/jenkins.service
- name: Template a file to /etc/systemd/system/jenkins.service
  template:
    src: ./jenkins.service
    dest: /etc/systemd/system/jenkins.service
  notify:
     - restart-jenkins

# Force all the handlers (trigger)     
- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

# Waiting for the Password File in the Jenkins Server
- name: Wait for the password file
  wait_for:
    path: /root/.jenkins/secrets/initialAdminPassword

# Print the Password    
- name: Get the password file
  shell: cat /root/.jenkins/secrets/initialAdminPassword
  register: res

- debug:
      var: res.stdout
