---
# tasks file for roles/jenkins
- name: install default-jre
  package:
    name: default-jre
    state: present
- name: install jenkins-war
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc
- name: Template a file to /etc/systemd/system/jenkins.service
  template:
    src: jenkins.service
    dest: /etc/systemd/system/jenkins.service
  notify:
  - jenkins
   