pipeline {
    agent any
    stages {
        stage('init') {
            steps {
                sh 'cd eswarkp/terraform && terraform init -no-color'
            }
        }
        stage('plan') {
            steps {
                sh 'cd eswarkp/terraform && terraform plan -no-color -out tf.plan'
            }
        }
        stage('apply') {
            steps {
                sh 'cd eswarkp/terraform && terraform apply -auto-approve tf.plan'
            }
        }
        stage('destroy') {
            steps {
                sh 'cd eswarkp/terraform && terraform destroy -auto-approve'
            }
        }
    }
}
