pipeline {
    agent any
    stages {

        stage('build docker-compose') {
            steps {
                sh 'docker-compose build'
            }
        }

        stage('run docker-compose') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}
