---
# handlers file for roles/jenkins
#Handler to restart Jenkins on trigger and start at the boot.
- name: restart-jenkins
  systemd:
    name: jenkins
    daemon_reload: yes
    state: restarted
    enabled: yes # Starts service at the boot.