---
# tasks file for roles/jenkins
- name: install default-jre
  package:
    name: default-jre
    state: present
- name: Download Jenkins war
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc
- name: Deploy Jenkins service file
  template:
    src: jenkins.service.template
    dest: /etc/systemd/system/jenkins.service
  notify:
    - jenkins restart
- name: Wait for the init password file
  wait_for:
    path: /root/.jenkins/secrets/initialAdminPassword
    timeout: 5
- name: Display init password
  shell: cat /root/.jenkins/secrets/initialAdminPassword
  register: result
- debug:
    msg: "{{ result }}"
- name: Wait for port 8080 to become open on the host
  wait_for:
    port: 8080
    delay: 2
    timeout: 5
- name: Check that a page returns a status 200 and fail if the word Unlock Jenkins is not in the page contents
  uri:
    url: http://localhost:8080
    return_content: yes
  register: this
  failed_when: "'Unlock Jenkins' not in this.content"