FROM ubuntu
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean && \
    apt-get install curl -y && \
    apt-get install wget -y && \
    mkdir /usr/tmp
    
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export=JAVA_HOME
RUN mkdir /root/tmp3
RUN mkdir /root/tmp2
COPY ./connect-node.sh /etc/tmp2/connect-node.sh
COPY ./connect.sh /etc/tmp2/connect.sh
RUN chmod +x /etc/tmp2/*
