--- 
- name: install java
  package: 
    name: default-jre
    state: present

- name: Download jenkins.war
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc


- name: Copy file jenkins service file
  copy:
    src: ./jenkins.service
    dest: /etc/systemd/system/
  notify:
    - restart service 

- name: Wait until the lock file is removed
  wait_for:
    path: /root/.jenkins/secrets/initialAdminPassword
    state: present


##/root/.jenkins/secrets/initialAdminPassword
