--- 
- name: install java
  package: 
    name: default-jre
    state: present

- name: Download jenkins.war
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc
