---
- name: install java-default
  package:
    name: default-jre
    state: present
- name: download war file
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc
# tasks file for roles/jenkins
