---
- name: install java-default
  package:
    name: default-jre
    state: present
- name: download war file
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc
- name: Deploy jenkins service
  template:
    src: jenkins.service
    dest: /etc/systemd/system/jenkins.service
- name: Restart jenskins system service
  systemd:
    name: jenkins
    state: restarted 
# tasks file for roles/jenkins
