---
# tasks file for roles/jenkins
#- name: Install the package "python-apt"
#  apt:
#    name: python-apt

- name: Install the package "default-jre"
  apt:
    name: default-jre

- name: Download jenkins war
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc
    mode: '0440'