pipeline {
    agent any
    stages {
        stage('ping') {
            steps {
                sh 'cd mukund-dev/ansible && ansible all -m ping'
            }
        }
        stage('playbook') {
            steps {
                sh 'cd mukund-dev/ansible && ansible-playbook *.yml -b'
            }
        }

        stage('check whether jenkins is up & running'){
            steps{
                sh 'curl --fail --silent --output /dev/null http://13.232.106.195:8080/'
            }

        }
    }
}
