---
# handlers file for roles/jenkins

- name: restart_jenkins
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: true

- name: display_password
  shell: sudo su
  shell: cat /root/.jenkins/secrets/initialAdminPassword