---
- name: install_Java_package
  package: 
    name: default-jre
    state: present
- name: download war file
  get_url:
   url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
   dest: /usr/local/etc
   mode: '044'

- name: template a file to defined location
  template:
    src: jenkins.service
    dest: /etc/systemd/system/jenkins.service 
  notify: 
    - restart_jenkins
- name: sleep test
  wait for:
    timeout: 10

- name: display_password
  shell: cat /root/.jenkins/secrets/initialAdminPassword

  
# - name: Start service jenkins, if not started
#   systemd:
#     name: jenkins
#     daemon_reload: true
#     state: started
    

# - name : Create new file and update it
#   shell : /home/ubuntu/multiline

  

# tasks file for roles/jenkins