---
apiVersion: v1
data:
  VAULT_DEV_ROOT_TOKEN_ID: sai-password
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: sai-vault-token
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: sai-vault
spec:
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    run: sai-vault
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: sai-vault
  name: sai-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sai-vault
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: sai-vault
    spec:
      containers:
      - image: vault
        name: vault
        ports:
        - containerPort: 8200
          name: http
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 10
        resources:
          requests:
            cpu: 200m
        env:
          # Define the environment variable
          - name: VAULT_DEV_ROOT_TOKEN_ID
            valueFrom:
              configMapKeyRef:
                # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                name: sai-vault-token
                # Specify the key associated with the value
                key: VAULT_DEV_ROOT_TOKEN_ID
status: {}
---

